# Image Scaling

In [1]:
pip install torch transformers tf-keras

Note: you may need to restart the kernel to use updated packages.


In [2]:
# Load model directly
from transformers import AutoImageProcessor, AutoModelForImageToImage

processor = AutoImageProcessor.from_pretrained("caidas/swin2SR-realworld-sr-x4-64-bsrgan-psnr")
model = AutoModelForImageToImage.from_pretrained("caidas/swin2SR-realworld-sr-x4-64-bsrgan-psnr")

preprocessor_config.json:   0%|          | 0.00/152 [00:00<?, ?B/s]

D:\Users\mohitg\AppData\Local\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in D:\Users\mohitg\.cache\huggingface\hub\models--caidas--swin2SR-realworld-sr-x4-64-bsrgan-psnr. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Using a slow image processor as `use_fast` is unset and a slow processor was saved

config.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/48.5M [00:00<?, ?B/s]

In [7]:
from PIL import Image
import requests

url = "https://huggingface.co/spaces/jjourney1125/swin2sr/resolve/main/samples/butterfly.jpg"
image = Image.open(requests.get(url, stream=True).raw)

In [8]:
inputs = processor(image, return_tensors="pt")

In [10]:
import torch
with torch.no_grad():
    outputs = model(**inputs)

In [11]:
import numpy as np
output = outputs.reconstruction.data.squeeze().float().cpu().clamp_(0, 1).numpy()
output = np.moveaxis(output, source=0, destination=-1)
output = (output * 255.0).round().astype(np.uint8)

In [12]:
print(output)

[[[ 46  33  24]
  [ 47  33  22]
  [ 48  34  22]
  ...
  [ 75  59  53]
  [ 76  60  53]
  [ 76  59  54]]

 [[ 42  31  23]
  [ 43  32  22]
  [ 45  33  21]
  ...
  [ 75  60  52]
  [ 76  59  53]
  [ 76  58  53]]

 [[ 39  30  23]
  [ 40  31  22]
  [ 40  31  22]
  ...
  [ 75  59  52]
  [ 75  59  52]
  [ 75  59  53]]

 ...

 [[145  70  56]
  [139  63  51]
  [128  52  41]
  ...
  [154  90  77]
  [154  90  76]
  [155  91  76]]

 [[146  68  55]
  [135  60  50]
  [126  49  42]
  ...
  [154  90  75]
  [155  90  77]
  [155  90  76]]

 [[143  66  58]
  [135  56  52]
  [127  47  44]
  ...
  [154  89  75]
  [155  89  76]
  [154  90  76]]]


In [13]:
from PIL import Image

img = Image.fromarray(output)
img.save("output.png")